### PR TITLE
Chrome 72 requires a secure page or localhost

### PR DESCRIPTION
**Pull request by JHartman5**

### CODE REVIEW

**Review by bikegriffith — APPROVED** [review]
Looks good to me!

**Review by leandromoreira — APPROVED** [review]

**Comment by JHartman5** [comment]
Whose back do I have to scratch to get a PR merged? :-)

**Comment by leandromoreira** [comment]
@towerz @jhonatangomes @joaopaulovieira they are your friends

**Review by joaopaulovieira — APPROVED** [review]

**Comment by joaopaulovieira** [comment]
Thanks @JHartman5 !

**Pull request merged**
